title:              현도리의 작은 공간
email:              hyeondori@kakao.com
description:        선한 의지로 더 밝은 내일을 만듭니다
author:             hyeondori
baseurl:            ""
url:                "https://hyeondori.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    hyeondori
# facebook_username:  StartBootstrap
instagram_username:  hyndri
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
